"""update celery_task_executions indexes

Revision ID: 104df0cdf946
Revises: abfb2b53b09f
Create Date: 2026-04-15 07:48:49.877311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '104df0cdf946'
down_revision: Union[str, None] = 'abfb2b53b09f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_name_args_hash'), table_name='celery_task_executions')
    op.create_index('ix_task_name_args_celery_hash', 'celery_task_executions', ['task_name', 'task_args_hash', 'celery_task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_name_args_celery_hash', table_name='celery_task_executions')
    op.create_index(op.f('ix_task_name_args_hash'), 'celery_task_executions', ['task_name', 'task_args_hash'], unique=True)
    # ### end Alembic commands ###
