"""create celery_task_executions table

Revision ID: abfb2b53b09f
Revises: 7f88f8a9753b
Create Date: 2026-04-15 07:31:43.789278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'abfb2b53b09f'
down_revision: Union[str, None] = '7f88f8a9753b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('celery_task_executions', sa.Column('task_args', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('celery_task_executions', 'task_arg')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('celery_task_executions', sa.Column('task_arg', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('celery_task_executions', 'task_args')
    # ### end Alembic commands ###
